### ISSUE TITLE
Implement for GMM-Based Mechanisms

### ISSUE THREAD

**Issue by v-nhandt21** [anandaswarup/TTS#1]
Do you follow the GMM-Based Mechanisms in the paper: LOCATION-RELATIVE ATTENTION MECHANISMS FOR ROBUST LONG-FORM SPEECH SYNTHESIS ?

**Comment by anandaswarup** [comment]
No. The attention mechanism which I use in my system is the Dynamic Convolution Attention described in Sec 2.4 of the paper (Location relative attention mechanisms for robust long-form speech synthesis)
